// Code generated by protoc-gen-go.
// source: broker2broker.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	broker2broker.proto
	broker2Controller.proto
	client2Server.proto
	clientServer.proto
	controller2Broker.proto
	message.proto
	metaData.proto
	server2Client.proto

It has these top-level messages:
	Broker2Controller
	Client2Server
	ClientServerHeader
	CreatTopicReq
	CreatTopicRsp
	DeleteTopicReq
	DeleteTopicRsp
	PublishReq
	PublishRsp
	GetPublisherPartitionReq
	GetPublisherPartitionRsp
	GetConsumerPartitionReq
	GetConsumerPartitionRsp
	SubscribePartitionReq
	SubscribePartitionRsp
	SubscribeTopicReq
	SubscribeTopicRsp
	RegisterConsumerReq
	RegisterConsumerRsp
	UnRegisterConsumerReq
	UnRegisterConsumerRsp
	CommitReadyNumReq
	CommitReadyNumReqRsp
	ChangeConsumerPartitionReq
	ChangeConsumerPartitionRsp
	PushMsgReq
	PushMsgRsp
	Controller2Broker
	Message
	InternalMessage
	Partition
	ListenAddr
	MetaData
	Topic
	Group
	Server2Client
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("broker2broker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 63 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2a, 0xca, 0xcf,
	0x4e, 0x2d, 0x32, 0x82, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x1c, 0x60, 0x2a, 0x39,
	0x3f, 0x47, 0x8a, 0x37, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x15, 0x22, 0x91, 0xc4, 0x06, 0xa6,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xa6, 0xc5, 0x9b, 0x36, 0x00, 0x00, 0x00,
}
