// Code generated by protoc-gen-go.
// source: client2Server.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	client2Server.proto
	server2Client.proto

It has these top-level messages:
	Client2Server
	Message
	Server2Client
	Partition
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client2ServerKey int32

const (
	Client2ServerKey_CreatTopic            Client2ServerKey = 0
	Client2ServerKey_GetPublisherPartition Client2ServerKey = 1
	Client2ServerKey_Publish               Client2ServerKey = 2
	Client2ServerKey_GetConsumerPartition  Client2ServerKey = 3
	Client2ServerKey_SubscribePartion      Client2ServerKey = 4
	Client2ServerKey_SubscribeTopic        Client2ServerKey = 5
	Client2ServerKey_RegisterConsumer      Client2ServerKey = 6
	Client2ServerKey_UnRegisterConsumer    Client2ServerKey = 7
)

var Client2ServerKey_name = map[int32]string{
	0: "CreatTopic",
	1: "GetPublisherPartition",
	2: "Publish",
	3: "GetConsumerPartition",
	4: "SubscribePartion",
	5: "SubscribeTopic",
	6: "RegisterConsumer",
	7: "UnRegisterConsumer",
}
var Client2ServerKey_value = map[string]int32{
	"CreatTopic":            0,
	"GetPublisherPartition": 1,
	"Publish":               2,
	"GetConsumerPartition":  3,
	"SubscribePartion":      4,
	"SubscribeTopic":        5,
	"RegisterConsumer":      6,
	"UnRegisterConsumer":    7,
}

func (x Client2ServerKey) String() string {
	return proto.EnumName(Client2ServerKey_name, int32(x))
}
func (Client2ServerKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// this is a comment
type Client2Server struct {
	Key          Client2ServerKey `protobuf:"varint,1,opt,name=key,enum=protocol.Client2ServerKey" json:"key,omitempty"`
	Topic        string           `protobuf:"bytes,2,opt,name=Topic" json:"Topic,omitempty"`
	Partition    string           `protobuf:"bytes,3,opt,name=Partition" json:"Partition,omitempty"`
	GroupName    string           `protobuf:"bytes,4,opt,name=GroupName" json:"GroupName,omitempty"`
	PartitionNum int32            `protobuf:"varint,5,opt,name=PartitionNum" json:"PartitionNum,omitempty"`
	Msg          *Message         `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *Client2Server) Reset()                    { *m = Client2Server{} }
func (m *Client2Server) String() string            { return proto.CompactTextString(m) }
func (*Client2Server) ProtoMessage()               {}
func (*Client2Server) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client2Server) GetKey() Client2ServerKey {
	if m != nil {
		return m.Key
	}
	return Client2ServerKey_CreatTopic
}

func (m *Client2Server) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Client2Server) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *Client2Server) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Client2Server) GetPartitionNum() int32 {
	if m != nil {
		return m.PartitionNum
	}
	return 0
}

func (m *Client2Server) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Message struct {
	Priority int32  `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Client2Server)(nil), "protocol.Client2Server")
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterEnum("protocol.Client2ServerKey", Client2ServerKey_name, Client2ServerKey_value)
}

func init() { proto.RegisterFile("client2Server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x7f, 0x4b, 0x29, 0x7f, 0x06, 0x7e, 0x64, 0x1d, 0xd1, 0xac, 0xc4, 0x43, 0x83, 0x97,
	0xc6, 0x18, 0x0e, 0x78, 0xf0, 0x01, 0x38, 0x70, 0x30, 0x12, 0x52, 0xf4, 0x01, 0xda, 0x66, 0x82,
	0x1b, 0xdb, 0x6e, 0xb3, 0xbb, 0x35, 0xe1, 0xdd, 0x7c, 0x10, 0x1f, 0xc7, 0xb4, 0x85, 0x02, 0x7a,
	0xda, 0xcc, 0xe7, 0xfb, 0xd9, 0xd9, 0x99, 0x85, 0xcb, 0x38, 0x91, 0x94, 0xd9, 0xf9, 0x86, 0xf4,
	0x27, 0xe9, 0x59, 0xae, 0x95, 0x55, 0xd8, 0xab, 0x8e, 0x58, 0x25, 0xd3, 0x6f, 0x06, 0xff, 0x17,
	0xa7, 0x06, 0x3e, 0x80, 0xf3, 0x41, 0x3b, 0xc1, 0x3c, 0xe6, 0x8f, 0xe6, 0x93, 0xd9, 0xc1, 0x9c,
	0x9d, 0x59, 0xcf, 0xb4, 0x0b, 0x4a, 0x0d, 0xc7, 0xe0, 0xbe, 0xaa, 0x5c, 0xc6, 0xa2, 0xe5, 0x31,
	0xbf, 0x1f, 0xd4, 0x05, 0xde, 0x42, 0x7f, 0x1d, 0x6a, 0x2b, 0xad, 0x54, 0x99, 0x70, 0xaa, 0xe4,
	0x08, 0xca, 0x74, 0xa9, 0x55, 0x91, 0xaf, 0xc2, 0x94, 0x44, 0xbb, 0x4e, 0x1b, 0x80, 0x53, 0x18,
	0x36, 0xea, 0xaa, 0x48, 0x85, 0xeb, 0x31, 0xdf, 0x0d, 0xce, 0x18, 0xde, 0x81, 0x93, 0x9a, 0xad,
	0xe8, 0x78, 0xcc, 0x1f, 0xcc, 0x2f, 0x8e, 0x33, 0xbe, 0x90, 0x31, 0xe1, 0x96, 0x82, 0x32, 0x9d,
	0x3e, 0x41, 0x77, 0x5f, 0xe3, 0x04, 0x7a, 0xb9, 0x96, 0x4a, 0x4b, 0x5b, 0x2f, 0xe6, 0x06, 0x4d,
	0x8d, 0xbc, 0xee, 0x55, 0xce, 0x3f, 0xac, 0x2e, 0xde, 0x7f, 0x31, 0xe0, 0xbf, 0xb7, 0xc5, 0x11,
	0xc0, 0x42, 0x53, 0x68, 0xab, 0x05, 0xf9, 0x3f, 0xbc, 0x81, 0xab, 0x25, 0xd9, 0x75, 0x11, 0x25,
	0xd2, 0xbc, 0x93, 0x6e, 0xc6, 0xe3, 0x0c, 0x07, 0xd0, 0xdd, 0x73, 0xde, 0x42, 0x01, 0xe3, 0x25,
	0xd9, 0x85, 0xca, 0x4c, 0x91, 0x9e, 0x6a, 0x0e, 0x8e, 0x81, 0x6f, 0x8a, 0xc8, 0xc4, 0x5a, 0x46,
	0x54, 0x71, 0x95, 0xf1, 0x36, 0x22, 0x8c, 0x1a, 0x5a, 0xbf, 0xe5, 0x96, 0x66, 0x40, 0x5b, 0x69,
	0x2c, 0xe9, 0x43, 0x23, 0xde, 0xc1, 0x6b, 0xc0, 0xb7, 0xec, 0x0f, 0xef, 0x46, 0x9d, 0xea, 0x3b,
	0x1e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xd4, 0x02, 0x19, 0xfa, 0x01, 0x00, 0x00,
}
