// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Priority int32  `protobuf:"varint,2,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Message) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type InternalMessage struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Priority int32  `protobuf:"varint,2,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Pos      int32  `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
	TryTimes int32  `protobuf:"varint,5,opt,name=tryTimes" json:"tryTimes,omitempty"`
	Timeout  int64  `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *InternalMessage) Reset()                    { *m = InternalMessage{} }
func (m *InternalMessage) String() string            { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()               {}
func (*InternalMessage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *InternalMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InternalMessage) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *InternalMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *InternalMessage) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *InternalMessage) GetTryTimes() int32 {
	if m != nil {
		return m.TryTimes
	}
	return 0
}

func (m *InternalMessage) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Partition struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Partition) Reset()                    { *m = Partition{} }
func (m *Partition) String() string            { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()               {}
func (*Partition) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ListenAddr struct {
	ClientListenAddr string `protobuf:"bytes,1,opt,name=clientListenAddr" json:"clientListenAddr,omitempty"`
	BrokerListenAddr string `protobuf:"bytes,2,opt,name=BrokerListenAddr" json:"BrokerListenAddr,omitempty"`
}

func (m *ListenAddr) Reset()                    { *m = ListenAddr{} }
func (m *ListenAddr) String() string            { return proto.CompactTextString(m) }
func (*ListenAddr) ProtoMessage()               {}
func (*ListenAddr) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ListenAddr) GetClientListenAddr() string {
	if m != nil {
		return m.ClientListenAddr
	}
	return ""
}

func (m *ListenAddr) GetBrokerListenAddr() string {
	if m != nil {
		return m.BrokerListenAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterType((*InternalMessage)(nil), "protocol.InternalMessage")
	proto.RegisterType((*Partition)(nil), "protocol.Partition")
	proto.RegisterType((*ListenAddr)(nil), "protocol.ListenAddr")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4d, 0x4a, 0x04, 0x31,
	0x10, 0x85, 0x49, 0xf7, 0xfc, 0x75, 0xe1, 0xcf, 0x90, 0x55, 0x70, 0xd5, 0xf4, 0xaa, 0x71, 0xe1,
	0x66, 0x4e, 0xa0, 0x1b, 0x11, 0x14, 0x24, 0x78, 0x81, 0x38, 0x09, 0x43, 0x61, 0x27, 0x69, 0x2a,
	0xe5, 0x62, 0x4e, 0xe2, 0x75, 0x25, 0x69, 0x47, 0x85, 0xde, 0xce, 0x2a, 0xef, 0x7d, 0x79, 0xf5,
	0x28, 0x28, 0xb8, 0xf4, 0x2e, 0x25, 0x73, 0x70, 0x77, 0x23, 0x45, 0x8e, 0x72, 0x53, 0x9e, 0x7d,
	0x1c, 0xba, 0x47, 0x58, 0xbf, 0x4c, 0x5f, 0xf2, 0x0a, 0x2a, 0xb4, 0x4a, 0xb4, 0xa2, 0x5f, 0xea,
	0x0a, 0xad, 0xbc, 0x81, 0xcd, 0x48, 0x18, 0x09, 0xf9, 0xa8, 0xaa, 0x42, 0x7f, 0xbd, 0xdc, 0x42,
	0xed, 0xd3, 0x41, 0xd5, 0xad, 0xe8, 0x2f, 0x74, 0x96, 0xdd, 0x97, 0x80, 0xeb, 0xa7, 0xc0, 0x8e,
	0x82, 0x19, 0xce, 0xd2, 0x98, 0xc9, 0x18, 0x93, 0x5a, 0x94, 0x60, 0x96, 0x79, 0x9e, 0xe9, 0xf8,
	0x86, 0xde, 0x25, 0xb5, 0x9c, 0xe6, 0x4f, 0x5e, 0x2a, 0x58, 0x33, 0x7a, 0x17, 0x3f, 0x59, 0xad,
	0x5a, 0xd1, 0xd7, 0xfa, 0x64, 0xbb, 0x1d, 0x34, 0xaf, 0x86, 0x18, 0x19, 0x63, 0x90, 0x12, 0x16,
	0xc1, 0x78, 0x57, 0x96, 0x6a, 0x74, 0xd1, 0x99, 0x19, 0x6b, 0xa9, 0xac, 0xd4, 0xe8, 0xa2, 0x3b,
	0x0b, 0xf0, 0x8c, 0x89, 0x5d, 0xb8, 0xb7, 0x96, 0xe4, 0x2d, 0x6c, 0xf7, 0x03, 0xba, 0xc0, 0x7f,
	0xec, 0xa7, 0x61, 0xc6, 0x73, 0xf6, 0x81, 0xe2, 0x87, 0xa3, 0x7f, 0xd9, 0xa9, 0x79, 0xc6, 0xdf,
	0x57, 0xe5, 0x0e, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x6c, 0x5b, 0x94, 0x9f, 0x01,
	0x00, 0x00,
}
