// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RetStatus int32

const (
	RetStatus_Successs  RetStatus = 0
	RetStatus_Fail      RetStatus = 1
	RetStatus_QueueFull RetStatus = 2
)

var RetStatus_name = map[int32]string{
	0: "Successs",
	1: "Fail",
	2: "QueueFull",
}
var RetStatus_value = map[string]int32{
	"Successs":  0,
	"Fail":      1,
	"QueueFull": 2,
}

func (x RetStatus) String() string {
	return proto.EnumName(RetStatus_name, int32(x))
}
func (RetStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type Message struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Priority int32  `protobuf:"varint,2,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Message) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type InternalMessage struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Priority int32  `protobuf:"varint,2,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Pos      int32  `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
	TryTimes int32  `protobuf:"varint,5,opt,name=tryTimes" json:"tryTimes,omitempty"`
	Timeout  int64  `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *InternalMessage) Reset()                    { *m = InternalMessage{} }
func (m *InternalMessage) String() string            { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()               {}
func (*InternalMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *InternalMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InternalMessage) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *InternalMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *InternalMessage) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *InternalMessage) GetTryTimes() int32 {
	if m != nil {
		return m.TryTimes
	}
	return 0
}

func (m *InternalMessage) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Partition struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Partition) Reset()                    { *m = Partition{} }
func (m *Partition) String() string            { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()               {}
func (*Partition) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ListenAddr struct {
	ClientListenAddr string `protobuf:"bytes,1,opt,name=clientListenAddr" json:"clientListenAddr,omitempty"`
	BrokerListenAddr string `protobuf:"bytes,2,opt,name=BrokerListenAddr" json:"BrokerListenAddr,omitempty"`
}

func (m *ListenAddr) Reset()                    { *m = ListenAddr{} }
func (m *ListenAddr) String() string            { return proto.CompactTextString(m) }
func (*ListenAddr) ProtoMessage()               {}
func (*ListenAddr) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *ListenAddr) GetClientListenAddr() string {
	if m != nil {
		return m.ClientListenAddr
	}
	return ""
}

func (m *ListenAddr) GetBrokerListenAddr() string {
	if m != nil {
		return m.BrokerListenAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterType((*InternalMessage)(nil), "protocol.InternalMessage")
	proto.RegisterType((*Partition)(nil), "protocol.Partition")
	proto.RegisterType((*ListenAddr)(nil), "protocol.ListenAddr")
	proto.RegisterEnum("protocol.RetStatus", RetStatus_name, RetStatus_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xdd, 0xed, 0xbf, 0xdd, 0xa1, 0xd5, 0x25, 0xa7, 0xe0, 0xa9, 0xec, 0xa9, 0xf4, 0xe0,
	0xc1, 0x3e, 0x81, 0x1e, 0x2a, 0x82, 0x82, 0xa6, 0xbe, 0x40, 0xdc, 0x0c, 0x25, 0x98, 0x4d, 0x4a,
	0x32, 0x39, 0xf4, 0x49, 0x7c, 0x5d, 0x49, 0xd6, 0xaa, 0xd0, 0xab, 0xa7, 0x7c, 0xdf, 0x2f, 0xdf,
	0x7c, 0x0c, 0x0c, 0x2c, 0x7a, 0x0c, 0x41, 0xee, 0xf1, 0xe6, 0xe0, 0x1d, 0x39, 0x56, 0xe5, 0xa7,
	0x73, 0xa6, 0x7d, 0x80, 0xd9, 0xf3, 0xf0, 0xc5, 0x2e, 0xa1, 0xd4, 0x8a, 0x17, 0xcb, 0x62, 0x35,
	0x11, 0xa5, 0x56, 0xec, 0x1a, 0xaa, 0x83, 0xd7, 0xce, 0x6b, 0x3a, 0xf2, 0x32, 0xd3, 0x1f, 0xcf,
	0x1a, 0x18, 0xf5, 0x61, 0xcf, 0x47, 0xcb, 0x62, 0x35, 0x17, 0x49, 0xb6, 0x9f, 0x05, 0x5c, 0x3d,
	0x5a, 0x42, 0x6f, 0xa5, 0xf9, 0x97, 0xc6, 0x44, 0x0e, 0x2e, 0xf0, 0x71, 0x0e, 0x26, 0x99, 0xe6,
	0xc9, 0x1f, 0xdf, 0x74, 0x8f, 0x81, 0x4f, 0x86, 0xf9, 0x93, 0x67, 0x1c, 0x66, 0xa4, 0x7b, 0x74,
	0x91, 0xf8, 0x74, 0x59, 0xac, 0x46, 0xe2, 0x64, 0xdb, 0x0d, 0xd4, 0x2f, 0xd2, 0x93, 0x26, 0xed,
	0x2c, 0x63, 0x30, 0xb6, 0xb2, 0xc7, 0xbc, 0x54, 0x2d, 0xb2, 0x4e, 0x4c, 0x2a, 0xe5, 0xf3, 0x4a,
	0xb5, 0xc8, 0xba, 0x55, 0x00, 0x4f, 0x3a, 0x10, 0xda, 0x3b, 0xa5, 0x3c, 0x5b, 0x43, 0xd3, 0x19,
	0x8d, 0x96, 0x7e, 0xd9, 0x77, 0xc3, 0x19, 0x4f, 0xd9, 0x7b, 0xef, 0x3e, 0xd0, 0xff, 0xc9, 0x0e,
	0xcd, 0x67, 0x7c, 0x7d, 0x0b, 0xb5, 0x40, 0xda, 0x91, 0xa4, 0x18, 0xd8, 0x1c, 0xaa, 0x5d, 0xec,
	0x3a, 0x0c, 0x21, 0x34, 0x17, 0xac, 0x82, 0xf1, 0x56, 0x6a, 0xd3, 0x14, 0x6c, 0x01, 0xf5, 0x6b,
	0xc4, 0x88, 0xdb, 0x68, 0x4c, 0x53, 0xbe, 0x4f, 0xf3, 0xed, 0x36, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb5, 0x2b, 0x1a, 0xf4, 0xd3, 0x01, 0x00, 0x00,
}
