// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	request.proto
	response.proto

It has these top-level messages:
	Request
	Message
	Response
	Partition
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestKey int32

const (
	RequestKey_CreatTopic            RequestKey = 0
	RequestKey_GetPublisherPartition RequestKey = 1
	RequestKey_Publish               RequestKey = 2
	RequestKey_GetConsumerPartition  RequestKey = 3
	RequestKey_Subscribe             RequestKey = 4
)

var RequestKey_name = map[int32]string{
	0: "CreatTopic",
	1: "GetPublisherPartition",
	2: "Publish",
	3: "GetConsumerPartition",
	4: "Subscribe",
}
var RequestKey_value = map[string]int32{
	"CreatTopic":            0,
	"GetPublisherPartition": 1,
	"Publish":               2,
	"GetConsumerPartition":  3,
	"Subscribe":             4,
}

func (x RequestKey) String() string {
	return proto.EnumName(RequestKey_name, int32(x))
}
func (RequestKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// this is a comment
type Request struct {
	Key          RequestKey `protobuf:"varint,1,opt,name=key,enum=protocol.RequestKey" json:"key,omitempty"`
	Topic        string     `protobuf:"bytes,2,opt,name=Topic" json:"Topic,omitempty"`
	Partition    string     `protobuf:"bytes,3,opt,name=Partition" json:"Partition,omitempty"`
	GroupName    string     `protobuf:"bytes,4,opt,name=GroupName" json:"GroupName,omitempty"`
	PartitionNum int32      `protobuf:"varint,5,opt,name=PartitionNum" json:"PartitionNum,omitempty"`
	Msg          *Message   `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetKey() RequestKey {
	if m != nil {
		return m.Key
	}
	return RequestKey_CreatTopic
}

func (m *Request) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Request) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *Request) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Request) GetPartitionNum() int32 {
	if m != nil {
		return m.PartitionNum
	}
	return 0
}

func (m *Request) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Message struct {
	Priority int32  `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	Msg      []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterEnum("protocol.RequestKey", RequestKey_name, RequestKey_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbb, 0x4e, 0xf3, 0x40,
	0x14, 0x84, 0xff, 0x8d, 0xe3, 0x5c, 0x4e, 0x2e, 0xf2, 0x7f, 0x14, 0xa4, 0x05, 0x51, 0x58, 0x46,
	0x42, 0x16, 0x85, 0x8b, 0x50, 0xf0, 0x00, 0x29, 0x5c, 0x20, 0xa2, 0x68, 0xe1, 0x05, 0x6c, 0xeb,
	0x28, 0xac, 0x88, 0xb3, 0x66, 0x2f, 0x45, 0xde, 0x91, 0x87, 0x42, 0xbe, 0x60, 0x43, 0xb5, 0x9a,
	0xf9, 0x66, 0x8f, 0x66, 0x60, 0xa5, 0xe9, 0xd3, 0x91, 0xb1, 0x49, 0xa5, 0x95, 0x55, 0x38, 0x6b,
	0x9e, 0x42, 0x9d, 0xa2, 0x2f, 0x06, 0x53, 0xd1, 0x32, 0xbc, 0x07, 0xef, 0x83, 0x2e, 0x9c, 0x85,
	0x2c, 0x5e, 0x6f, 0x37, 0xc9, 0x4f, 0x26, 0xe9, 0xf8, 0x33, 0x5d, 0x44, 0x1d, 0xc0, 0x0d, 0xf8,
	0x6f, 0xaa, 0x92, 0x05, 0x1f, 0x85, 0x2c, 0x9e, 0x8b, 0x56, 0xe0, 0x2d, 0xcc, 0x0f, 0x99, 0xb6,
	0xd2, 0x4a, 0x75, 0xe6, 0x5e, 0x43, 0x06, 0xa3, 0xa6, 0xa9, 0x56, 0xae, 0xda, 0x67, 0x25, 0xf1,
	0x71, 0x4b, 0x7b, 0x03, 0x23, 0x58, 0xf6, 0xd1, 0xbd, 0x2b, 0xb9, 0x1f, 0xb2, 0xd8, 0x17, 0x7f,
	0x3c, 0xbc, 0x03, 0xaf, 0x34, 0x47, 0x3e, 0x09, 0x59, 0xbc, 0xd8, 0xfe, 0x1f, 0xda, 0xbd, 0x90,
	0x31, 0xd9, 0x91, 0x44, 0x4d, 0xa3, 0x27, 0x98, 0x76, 0x1a, 0x6f, 0x60, 0x56, 0x69, 0xa9, 0xb4,
	0xb4, 0xed, 0x24, 0x5f, 0xf4, 0x1a, 0x83, 0xf6, 0x56, 0xdd, 0x7f, 0xd9, 0x7c, 0x7c, 0x28, 0x01,
	0x86, 0x99, 0xb8, 0x06, 0xd8, 0x69, 0xca, 0x6c, 0xb3, 0x2c, 0xf8, 0x87, 0xd7, 0x70, 0x95, 0x92,
	0x3d, 0xb8, 0xfc, 0x24, 0xcd, 0x3b, 0xe9, 0xbe, 0x57, 0xc0, 0x70, 0x01, 0xd3, 0xce, 0x0f, 0x46,
	0xc8, 0x61, 0x93, 0x92, 0xdd, 0xa9, 0xb3, 0x71, 0xe5, 0xef, 0x98, 0x87, 0x2b, 0x98, 0xbf, 0xba,
	0xdc, 0x14, 0x5a, 0xe6, 0x14, 0x8c, 0xf3, 0x49, 0x53, 0xff, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xde, 0x2e, 0x48, 0xfd, 0x98, 0x01, 0x00, 0x00,
}
